#ifndef CHESS_SETTINGS_H
#define CHESS_SETTINGS_H
#include <stdio.h>
#include <assert.h>
#include "figure_info.h"
#include "chess_coord.h"
#include "chess_coord_tree.h"
#include "chess_coord_array.h"
#include "chess_coord_tree_array.h"
#endif //CHESS_SETTINGS_H